project: "SLUv1"
embed_model: "ResNet50_FMOW_RGB_GASSL"
model: 'MLPClassifier'
model_params:
    hidden_layer_sizes: [(50, 50, 50), (50, 100, 50), (50, 100, 100, 50), (100, )]
    activation: ['tanh', 'relu']
    solver: ['lbfgs', sgd', 'adam']
    alpha: [0.0001, 0.001, 0.01, 0.1]
    learning_rate: ['constant','adaptive']
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "RandomizedSearchCV"
n_splits: 5
cv_params:
   n_iter: 100
   refit: 'f1_score'
   verbose: 1
   n_jobs: -1