project: "SLUv1"
embed_model: "ScaleMAE_FMOW_RGB"
model: 'SVC'
model_params:
    kernel: ['linear', 'poly', 'rbf', 'sigmoid']
    gamma: [1, 0.1, 0.01, 0.001, 0.0001]
    C: [0.001, 0.01, 0.1, 1.0, 10]
    class_weight: ["balanced"]
selector: 
selector_params:
scalers: ['MinMaxScaler', 'StandardScaler', 'RobustScaler']
cv: "RandomizedSearchCV"
n_splits: 5
cv_params:
   n_iter: 100
   refit: 'f1_score'
   verbose: 1
   n_jobs: -1
